/**
 * Author: Jack Robbins
 * This class implements a Huffman encoding tree based on an inputted frequency map. This frequency
 * map can be generated by any text file from the main class
 */

import java.util.PriorityQueue;
import java.util.Map;


public class HuffmanEncoder{
	private	PriorityQueue<HuffmanNode> queue;
	private Map<Character, Integer> frequencies;
	private HuffmanNode root;
	int totalBits;

	public HuffmanEncoder(Map<Character, Integer> frequencies){
		this.frequencies = frequencies;	

		char[] characters = new char[frequencies.keySet().toArray().length];
		int[] charFreq = new int[characters.length];

		for(int i = 0; i < characters.length; i++){
			characters[i] = (char)frequencies.keySet().toArray()[i];
			charFreq[i] = frequencies.get(characters[i]);	
		}				


		this.root = null;
		this.totalBits = 0;
		queue = new PriorityQueue<HuffmanNode>(new HuffmanComparator());

		System.out.println("\n================ Character Frequencies ================\n");
		for(int i = 0; i < characters.length; i++){
			if(characters[i] == '\n'){
				continue;
			}

			System.out.println("Character: " + characters[i] + ", frequency: " + charFreq[i]);
			queue.add(new HuffmanNode(characters[i], charFreq[i]));
		}
	}


	public void generateHuffmanCodes(){
		System.out.println("\n=============== Huffman Codes =====================\n");
		while(this.queue.size() > 1){
			HuffmanNode x = queue.poll();

			HuffmanNode y = queue.poll();

			HuffmanNode f = new HuffmanNode();

			f.setData(x.getData() + y.getData());	
			f.setChar('$');

			f.setLeftChild(x);	
			f.setRightChild(y);	
			
			this.root = f;

			queue.add(f);
		}

		printCode(root, "");

		System.out.println("\nTotal bytes needed: " + totalBits / 8);

		System.out.println("===================================================");
	}


	public void printCode(HuffmanNode root, String byteString){
		if(root == null){
			return;
		}

		if(root.getLeft() == null && root.getRight() == null && root.getData() != '\n'){
			System.out.printf("Character: %1c, Encoding: %15s, Bits needed: %2d\n", root.getChar(), byteString, byteString.length());
			totalBits += byteString.length() * frequencies.get(root.getChar());
			return;
		}

		printCode(root.getLeft(), byteString + "0");
		printCode(root.getRight(), byteString + "1");
	}
}
